# Site Information
title: 卡比
description: "一窍不通大混子，想要成为AI infra糕手。"
url: https://c1lovez1.github.io
repo: c1lovez1/c1lovez1.github.io
lang: zh-CN
timezone: Africa/El_Aaiun

# Social Media and External URLs
github: c1lovez1
zhihu: 暂定
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "About"
    url: "/about.html"
  - title: "Weekly"
    url: "https://zhg-weekly.vercel.app/"

# SEO and Analytics
google_analytics: G-PL13W62QF9

# Build Settings
paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
future: true
highlighter: rouge
markdown: kramdown
permalink: /:year-:month-:day/:title.html
sass:
  sass_dir: _sass
  style: compressed

collections:
  posts:
    output: true
    permalink: /:year-:month-:day/:title.html
  posts_en:
    output: false
    permalink: /en/:year-:month-:day/:title.html
    sort_by: date

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-pdf-embed
  - jekyll-sitemap
  - jekyll-feed

# Custom Site Settings
showBuyCoffee: true
payImage: //gw.alipayobjects.com/zos/k/vb/1.png
assetUrl: //www.armcvai.cn/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==